package views;

import javax.swing.table.DefaultTableModel;


public class PnlAdminDepartmentManage extends javax.swing.JPanel {

    /** Tạo mới form ManageDepartment */
    public PnlAdminDepartmentManage() {
        initComponents();

//        loadTableData();

       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlEditDepartment = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        tfEditDepartmentID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEditDepartmentName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        pnlAddDepartment = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        tfAddDepartmentID = new javax.swing.JTextField();
        tfAddDepartmentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        spnlDepartmentData = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(791, 655));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlEditDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sửa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlEditDepartment.setPreferredSize(new java.awt.Dimension(707, 80));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save.png"))); // NOI18N
        btnUpdate.setText("Lưu");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tfEditDepartmentID.setEditable(false);
        tfEditDepartmentID.setEnabled(false);

        jLabel4.setText("Mã phòng ban");

        jLabel3.setText("Tên phòng ban");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditDepartmentLayout = new javax.swing.GroupLayout(pnlEditDepartment);
        pnlEditDepartment.setLayout(pnlEditDepartmentLayout);
        pnlEditDepartmentLayout.setHorizontalGroup(
            pnlEditDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEditDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tfEditDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlEditDepartmentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnUpdate});

        pnlEditDepartmentLayout.setVerticalGroup(
            pnlEditDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEditDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfEditDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlTop.add(pnlEditDepartment, java.awt.BorderLayout.CENTER);

        pnlAddDepartment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlAddDepartment.setPreferredSize(new java.awt.Dimension(707, 80));

        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_add.png"))); // NOI18N
        btnAddNew.setText("Tạo mới");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        tfAddDepartmentID.setEditable(false);
        tfAddDepartmentID.setEnabled(false);

        jLabel6.setText("Mã phòng ban");

        jLabel5.setText("Tên phòng ban");

        javax.swing.GroupLayout pnlAddDepartmentLayout = new javax.swing.GroupLayout(pnlAddDepartment);
        pnlAddDepartment.setLayout(pnlAddDepartmentLayout);
        pnlAddDepartmentLayout.setHorizontalGroup(
            pnlAddDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAddDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(tfAddDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pnlAddDepartmentLayout.setVerticalGroup(
            pnlAddDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(jLabel6)
                    .addComponent(tfAddDepartmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfAddDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlTop.add(pnlAddDepartment, java.awt.BorderLayout.PAGE_START);

        add(pnlTop, java.awt.BorderLayout.PAGE_START);

        pnlBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng ban", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlBottom.setLayout(new java.awt.BorderLayout());

        spnlDepartmentData.setBorder(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnlDepartmentData.setViewportView(tblData);

        pnlBottom.add(spnlDepartmentData, java.awt.BorderLayout.CENTER);

        add(pnlBottom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
//        if (validateAddNew()) {
//            Department deptObj = new Department();
//            deptObj.setDepartmentID(0);
//            deptObj.setDepartmentName(tfAddDepartmentName.getText());
//
//            try {
//                DepartmentDAO.insertDepartment(deptObj);
//                JOptionPane.showMessageDialog(null, "Phòng ban mới được đưa vào thành công");
//                loadTableData();
//                tfAddDepartmentName.setText("");
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(null, "Không chèn được !", "Chèn lỗi", JOptionPane.ERROR_MESSAGE);
//                ex.printStackTrace();
//            } catch (ClassNotFoundException ex) {
//                JOptionPane.showMessageDialog(null, "Không chèn được !", "Chèn lỗi", JOptionPane.ERROR_MESSAGE);
//                ex.printStackTrace();
//            }
//        }
//        
}//GEN-LAST:event_btnAddNewActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
//        getEditData();
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        if (tfEditDepartmentID.getText().compareTo("") != 0) {
//            if (validateEdit()) {
//                Department deptObj = new Department();
//                deptObj.setDepartmentID(Integer.parseInt(tfEditDepartmentID.getText()));
//                deptObj.setDepartmentName(tfEditDepartmentName.getText());
//
//                try {
//                    DepartmentDAO.updateDepartment(deptObj);
//                    JOptionPane.showMessageDialog(null, "Phòng ban được cập nhật thành công");
//                    loadTableData();
//                } catch (SQLException ex) {
//                    JOptionPane.showMessageDialog(null, "Không cập nhật !", "Cập nhật lỗi", JOptionPane.ERROR_MESSAGE);
//                    ex.printStackTrace();
//                } catch (ClassNotFoundException ex) {
//                    JOptionPane.showMessageDialog(null, "Không cập nhật !", "Cập nhật lỗi", JOptionPane.ERROR_MESSAGE);
//                    ex.printStackTrace();
//                }
//            }
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Bạn phải chọn một hàng ở dưới!!!",
//                    "Không chọn hàng nào", JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        if (tblData.getSelectedRowCount() != 0) {
//            if (validateDelete()) {//Ensure
//                if (JOptionPane.showConfirmDialog(null,
//                        " Bạn có thực sự muốn xóa Phòng ban này ?",
//                        "Xác nhận xóa",
//                        JOptionPane.OK_CANCEL_OPTION)
//                        == JOptionPane.OK_OPTION) {
//                    try {
//
//                        DepartmentDAO.deleteDepartment(Integer.parseInt(tfEditDepartmentID.getText()));
//                        JOptionPane.showMessageDialog(null, "Xóa thành công");
//                        loadTableData();
//                        tfEditDepartmentID.setText("");
//                        tfEditDepartmentName.setText("");
//
//                    } catch (SQLException ex) {
//                        JOptionPane.showMessageDialog(null, "Không xóa được!", "Xóa bị lỗi", JOptionPane.ERROR_MESSAGE);
//                        ex.printStackTrace();
//                    } catch (ClassNotFoundException ex) {
//                        JOptionPane.showMessageDialog(null, "Không xóa được!", "Xóa bị lỗi", JOptionPane.ERROR_MESSAGE);
//                        ex.printStackTrace();
//                    }
//
//                }
//            }
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDataCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblDataCaretPositionChanged
    }//GEN-LAST:event_tblDataCaretPositionChanged

    private void tblDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDataKeyPressed
    }//GEN-LAST:event_tblDataKeyPressed

    private void tblDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDataKeyTyped
    }//GEN-LAST:event_tblDataKeyTyped

    private void tblDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDataKeyReleased
        getEditData();
    }//GEN-LAST:event_tblDataKeyReleased

    //Xác nhận hình thức trước khi ADDnew
//    private boolean validateAddNew() {
//        String msg = "";
//        /*Kiểm tra tên phòng ban có trống?*/
//        if (!ValidateFormTools.isFilledTextField(tfAddDepartmentName, true))//cắt các văn bản trong tfAddDepartmentName , kiểm tra trống
//        {
//            msg += "\n- Tên Phòng ban không thể để trống";
//        }
//        tfAddDepartmentName.setText(tfAddDepartmentName.getText().trim());
//
//
//        if (msg.compareTo("") != 0) {
//            JOptionPane.showMessageDialog(null,
//                    "Có một số lỗi" + msg,
//                    "Thêm mới lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//        } else {
//            return true;
//        }
//    }

    //Xác nhận xóa Phòng ban nếu Phòng ban không có nhân viên
//    private boolean validateDelete() {
//        int rowIndex = tblData.getSelectedRow();
//        int EmpNo = Integer.parseInt(tblModel.getValueAt(rowIndex, 2).toString());
//        int ToNo = Integer.parseInt(tblModel.getValueAt(rowIndex, 3).toString());
//        int FromNo = Integer.parseInt(tblModel.getValueAt(rowIndex, 4).toString());
//        if (EmpNo == 0 && ToNo == 0 & FromNo == 0)//Đảm bảo không có đối tượng phụ thuộc
//        {
//            return true;
//        } else {
//            JOptionPane.showMessageDialog(null,
//                    "Bạn không thể xóa Phòng ban này.\n  Có số nhân viên thuộc phòng ban này",
//                    "Xóa lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//    }

    //Nhận dữ liệu từ hàng chọn và tải dữ liệu vào bảng chỉnh sửa
    private void getEditData() {
        int rowIndex = tblData.getSelectedRow();
        tfEditDepartmentID.setText(tblModel.getValueAt(rowIndex, 0).toString());
        tfEditDepartmentName.setText(tblModel.getValueAt(rowIndex, 1).toString());
    }

    //Xác định đk trước khi thực hiện chỉnh sửa
//    private boolean validateEdit() {
//        String msg = "";
//        if (!ValidateFormTools.isFilledTextField(tfEditDepartmentName, true))//cắt các văn bản trong tftfEditDepartmentName, kiểm tra trống
//        {
//            msg += "\n- Tên phòng ban không thể để trống";
//        }
//        tfEditDepartmentName.setText(tfEditDepartmentName.getText().trim());
//        if (msg.compareTo("") != 0) {
//            JOptionPane.showMessageDialog(null,
//                    "Có lỗi" + msg,
//                    "Sửa lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//        } else {
//            return true;
//        }
//    }

    //Tải dữ liệu vào bảng
//    private void loadTableData() {
//        try {
//            List<Department> departmentList = DepartmentDAO.selectAllDepartment();
//            tblModel = new DefaultTableModel();
//            tblModel.addColumn("STT");
//            tblModel.addColumn("Tên Phòng ban");
//            tblModel.addColumn("Số nhân viên");
//             for (Department department : departmentList) {
//                Vector<String> row = new Vector<String>();
//                row.addElement(String.valueOf(department.getDepartmentID()));
//                row.addElement(department.getDepartmentName());
//                row.addElement(String.valueOf(department.getNumOfEmployee()));
//                tblModel.addRow(row);
//            }
//            tblData.setModel(tblModel);
//        } catch (ClassNotFoundException ex) {
//            JOptionPane.showMessageDialog(null,
//                    "Không thể tải được cơ sở dữ liệu",
//                    "Lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null,
//                    "Không thể tải Phòng ban trong cơ sở dư liệu",
//                    "Lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
//        }
//
//    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddNew;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel pnlAddDepartment;
    public javax.swing.JPanel pnlBottom;
    public javax.swing.JPanel pnlEditDepartment;
    public javax.swing.JPanel pnlTop;
    public javax.swing.JScrollPane spnlDepartmentData;
    public javax.swing.JTable tblData;
    public javax.swing.JTextField tfAddDepartmentID;
    public javax.swing.JTextField tfAddDepartmentName;
    public javax.swing.JTextField tfEditDepartmentID;
    public javax.swing.JTextField tfEditDepartmentName;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel tblModel = new DefaultTableModel();
}
