package views;

public class PnlAdminProjectManage extends javax.swing.JPanel {

    /** Creates new form ProjectUIPanel */
    public PnlAdminProjectManage() {
        initComponents();
//        tblModel = new DefaultTableModel();
//      
//        loadTableData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlAddNew = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfAddNewProjectID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfAddNewProjectName = new javax.swing.JTextField();
        btnAddNew = new javax.swing.JButton();
        pnlEdit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEditProjectID = new javax.swing.JTextField();
        tfEditProjectName = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        sclPaneData = new javax.swing.JScrollPane();
        sclPaneData1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(791, 655));
        setMinimumSize(new java.awt.Dimension(791, 655));
        setPreferredSize(new java.awt.Dimension(791, 655));
        setLayout(new java.awt.BorderLayout());

        pnlTop.setPreferredSize(new java.awt.Dimension(671, 160));
        pnlTop.setRequestFocusEnabled(false);
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlAddNew.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm mới dự án", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlAddNew.setPreferredSize(new java.awt.Dimension(671, 80));

        jLabel1.setText("Mã dự án");

        tfAddNewProjectID.setEditable(false);
        tfAddNewProjectID.setEnabled(false);

        jLabel2.setText("Tên dự án");

        btnAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_add.png"))); // NOI18N
        btnAddNew.setText("Thêm mới");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddNewLayout = new javax.swing.GroupLayout(pnlAddNew);
        pnlAddNew.setLayout(pnlAddNewLayout);
        pnlAddNewLayout.setHorizontalGroup(
            pnlAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAddNewProjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAddNewProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        pnlAddNewLayout.setVerticalGroup(
            pnlAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAddNewProjectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfAddNewProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNew))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlTop.add(pnlAddNew, java.awt.BorderLayout.NORTH);

        pnlEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlEdit.setPreferredSize(new java.awt.Dimension(671, 80));

        jLabel4.setText("Mã dự án");

        jLabel3.setText("Tên dự án");

        tfEditProjectID.setEditable(false);
        tfEditProjectID.setEnabled(false);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_save.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEditProjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEditProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEditProjectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfEditProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnlTop.add(pnlEdit, java.awt.BorderLayout.CENTER);

        add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dự án", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        pnlBottom.setLayout(new java.awt.BorderLayout());

        sclPaneData.setBorder(null);

        sclPaneData1.setBorder(null);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sclPaneData1.setViewportView(tblData);

        sclPaneData.setViewportView(sclPaneData1);

        pnlBottom.add(sclPaneData, java.awt.BorderLayout.CENTER);

        add(pnlBottom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
//        if (validateAddNew()) {
//            Project proj = new Project(tfAddNewProjectName.getText());
//            try {
//                ProjectDAO.insertProject(proj);
//                tfAddNewProjectName.setText("");
//                loadTableData();
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(null,
//                        "Không thể thêm dự án vao CSDL",
//                        "Lỗi thêm mới",
//                        JOptionPane.ERROR_MESSAGE);
//                Logger.getLogger(PnlAdminProjectManage.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                JOptionPane.showMessageDialog(null,
//                        "Không thể thêm dự án vao CSDL",
//                        "Lỗi thêm mới",
//                        JOptionPane.ERROR_MESSAGE);
//                Logger.getLogger(PnlAdminProjectManage.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void tblDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDataKeyReleased
//        loadEditData();
}//GEN-LAST:event_tblDataKeyReleased

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
//        loadEditData();
}//GEN-LAST:event_tblDataMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
//        if (tblData.getSelectedRow() != -1) {
//            if (validateUpdate()) {
//                int rowI = tblData.getSelectedRow();
//                Project proj = projectList.get(rowI);
//                proj.setProjectName(tfEditProjectName.getText());
//                try {
//                    ProjectDAO.updateProject(proj);
//                    tfEditProjectID.setText("");
//                    tfEditProjectName.setText("");
//                    loadTableData();
//                } catch (SQLException ex) {
//                    Logger.getLogger(PnlAdminProjectManage.class.getName()).log(Level.SEVERE, null, ex);
//                } catch (ClassNotFoundException ex) {
//                    Logger.getLogger(PnlAdminProjectManage.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "Bạn phải chọn một hàng trong bảng dưới đây.",
//                    "Không chọn hàng", JOptionPane.INFORMATION_MESSAGE);
//        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        System.out.println(tblData.getSelectedRow());
//        if (tblData.getSelectedRow() != -1) {
//            if (validateDelete()) {
//                if (JOptionPane.showConfirmDialog(null,
//                        "Bạn có thực sự muốn xóa dự án này ?",
//                        "Xác nhận xóa",
//                        JOptionPane.OK_CANCEL_OPTION)
//                        == JOptionPane.OK_OPTION) {
//                    try {
//                        ProjectDAO.deleteProject(Integer.parseInt(tfEditProjectID.getText()));
//                        tfEditProjectID.setText("");
//                        tfEditProjectName.setText("");
//                        loadTableData();
//                    } catch (SQLException ex) {
//                        JOptionPane.showMessageDialog(null,
//                                "Xóa không thành công",
//                                "Lỗi xóa",
//                                JOptionPane.ERROR_MESSAGE);
//                    } catch (ClassNotFoundException ex) {
//                        JOptionPane.showMessageDialog(null,
//                                "Xóa không thành công",
//                                "Lỗi xóa",
//                                JOptionPane.ERROR_MESSAGE);
//                    }
//                }
//
//            }
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

//    private boolean validateAddNew()//Validate to add new Project
//    {
//        StringBuilder msg = new StringBuilder();
//        if (!ValidateFormTools.isFilledTextField(tfAddNewProjectName, true)) {
//            msg.append("\n - Tên dự án không được để trống.");
//        }
//
//        if (msg.toString().compareTo("") != 0) {
//            JOptionPane.showMessageDialog(null,
//                    "Có 1 số lỗi" + msg,
//                    "Lỗi thêm mới",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//        } else {
//            return true;
//        }
//    }
//
//    private boolean validateDelete() //Ensure there are no Transfer or Employee link to this Project
//    {
//        int rowI = tblData.getSelectedRow();
//        Project proj = projectList.get(rowI);
//
//        if (proj.getFromTransferCount() == 0 && proj.getToTransferCount() == 0 && proj.getNumberOfEmployees() == 0) {
//            return true;
//        } else {
//            JOptionPane.showMessageDialog(null,
//                    "Bạn không thể xóa những dự án này.",
//                    "Lỗi xóa",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//
//        }
//    }
//
//    private boolean validateUpdate() //Validate to edit an Project
//    {
//        StringBuilder msg = new StringBuilder();
//        if (!ValidateFormTools.isFilledTextField(tfEditProjectName, true)) {
//            msg.append("\n - Tên dự án không được để trống.");
//        }
//
//        if (msg.toString().compareTo("") != 0) {
//            JOptionPane.showMessageDialog(null,
//                    "Có 1 số lỗi" + msg,
//                    "Lỗi sửa",
//                    JOptionPane.ERROR_MESSAGE);
//            return false;
//        } else {
//            return true;
//        }
//    }
//
//    private void loadEditData()//Load data to edit form, when user click or press up/down key on table
//    {
//        if (tblData.getSelectedRow() != -1) {
//            int rowI = tblData.getSelectedRow();
//            Project proj = projectList.get(rowI);
//            tfEditProjectID.setText(String.valueOf(proj.getProjectID()));
//            tfEditProjectName.setText(String.valueOf(proj.getProjectName()));
//        }
//    }
//
//    private void loadTableData()//Load data from database to table
//    {
//        try {
//            projectList = ProjectDAO.selectAllProject();
//            tblModel = new DefaultTableModel();
//            tblModel.addColumn("Mã dự án");
//            tblModel.addColumn("Tên dự án");
//            tblModel.addColumn("Số nhân viên");
//           for (Project project : projectList) {
//                Vector<String> row = new Vector<String>();
//                row.addElement(String.valueOf(project.getProjectID()));
//                row.addElement(project.getProjectName());
//                row.addElement(String.valueOf(project.getNumberOfEmployees()));
//               tblModel.addRow(row);
//            }
//            tblData.setModel(tblModel);
//        } catch (ClassNotFoundException ex) {
//            JOptionPane.showMessageDialog(null,
//                    "Không thể load từ CSDL",
//                    "Lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null,
//                     "Không thể load từ CSDL",
//                    "Lỗi",
//                    JOptionPane.ERROR_MESSAGE);
//            ex.printStackTrace();
//        }
//
//    }
//
//   
//    DefaultTableModel tblModel;
//    List<Project> projectList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddNew;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnUpdate;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel pnlAddNew;
    public javax.swing.JPanel pnlBottom;
    public javax.swing.JPanel pnlEdit;
    public javax.swing.JPanel pnlTop;
    public javax.swing.JScrollPane sclPaneData;
    public javax.swing.JScrollPane sclPaneData1;
    public javax.swing.JTable tblData;
    public javax.swing.JTextField tfAddNewProjectID;
    public javax.swing.JTextField tfAddNewProjectName;
    public javax.swing.JTextField tfEditProjectID;
    public javax.swing.JTextField tfEditProjectName;
    // End of variables declaration//GEN-END:variables
}
